### ISSUE TITLE
Django 1.9 support

### ISSUE THREAD

**Issue by volodchenkov** [Kras4ooo/django-bitbucket-hook#1]
I have this warning:
`/home/izvr/Projects/ani/env/lib/python3.4/site-packages/django_bitbucket_hook/urls.py:8: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.`
So you can fix urls.py and add support for Django 1.9

**Comment by Kras4ooo** [comment]
Thanks for this issue. It is fixed.
